import Link from "next/link";
import type { Metadata } from "next";
import "./globals.css";
import ClientSideHeader from "@/components/clientsideHeader/clientsideHeader";

export const metadata: Metadata = {
    title: "Authentication by n8x",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-zinc-800">
                {children}
                <div className="w-full md:px-12 px-5 md:py-6 py-3 flex justify-between items-center fixed bottom-0 bg-zinc-800 border-t-[1px] border-zinc-700">
                    <div className="flex items-center justify-center w-full gap-20 text-xl">
                        <Link href='/users'><div className="hover:scale-110 hover:transition-all duration-500">Users</div></Link>
                        <Link href='/profile'><div className="hover:scale-110 hover:transition-all duration-500">Prof</div></Link>
                        <Link href='/chats'><div className="hover:scale-110 hover:transition-all duration-500">Chats</div></Link>
                    </div>
                </div>
            </body>
        </html>
    );
}
