import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Authentication by n8x",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-800">
        {children}
        </body>
    </html>
  );
}